### ISSUE TITLE
ability to turn nested dependencies selective on while globally off

### ISSUE THREAD

**Issue by stryba** [Spea/SpBowerBundle#106]
Maybe I missed it but it does not seem to be possible to turn off nested dependencies while turning it on selectively for specific packages. It would be nice to have this option as well.

**Comment by Spea** [comment]
Actually this is already possible:

```yml
sp_bower:
    assetic:
        nest_dependencies:
            all: false
            bootstrap: true
```

I also update the [configuration reference](https://github.com/Spea/SpBowerBundle/blob/master/Resources/doc/configuration_reference.md).
