### ISSUE TITLE
Timeout while checkout Fuelux 3.1.0-wip from Bower

### ISSUE THREAD

**Issue by reypm** [Spea/SpBowerBundle#109]
Following the `README` I have setup `bower.json` as follow:

```
{
    "name": "PlantillaBundle",
    "dependencies": {
        "jquery": "1.11.1",
        "jquery-migrate": "latest",
        "bootstrap": "latest",
        "font-awesome": "latest",
        "bootstrapvalidator": "0.5.2",
        "pwstrength-bootstrap": "latest",
        "select2": "latest",
        "fuelux": "3.1.0-wip",
        "moment": "latest",
        "x-editable": "latest",
        "datatables": "latest",
        "bootbox": "latest",
        "bootstrap-multiselect": "latest",
        "bootstrap-table": "latest"
    }
}
```

And at `config.yml` the config is this one:

```
sp_bower:
    bundles:
        PlantillaBundle: ~
    install_on_warmup: true
    allow_root: true
    keep_bowerrc: true
    assetic:
        enabled: false
        nest_dependencies: false
```

Any time I try to run the command `sp:bower:install` or `sp:bower:update` I got this error:

> [Symfony\Component\Process\Exception\ProcessTimedOutException]  
> The process "'/usr/bin/bower' '--allow-root' 'update'" exceeded the
> timeout of 600 seconds.

I tried setting the `timeout` on the `.bowerrc` but it's overwrited by bundle since the error persiste and I don't know what else to do. [Here](http://pastie.org/9632116) is the log for the command output, can any give me some ideas?
