### ISSUE TITLE
RuntimeException: An error occured while installing dependencies

### ISSUE THREAD

**Issue by nanoo-k** [Spea/SpBowerBundle#114]
I'm trying to run `app/console sp:bower:install` for the first time and I get this error:

```
$ app/console sp:bower:install

Installing bower dependencies for "MyProjectSiteBundle" into "/Users/<username>/<Symfony2 Project Name>/src/MyProject/Bundle/SiteBundle/Resources/config/bower/../../public/components"
sh: line 0: fg: no job control

[Sp\BowerBundle\Bower\Exception\RuntimeException]  
An error occured while installing dependencies
```

1) Here is my `config.yml`.

```
# SpBowerBundle Configuration
sp_bower:
    bin: usr/local/bin/bower
    bundles:
        MyProjectSiteBundle:
            config_dir: Resources/config/bower
```

2) I've included your bundle in `AppKernel.php`.

```
$bundles = array(
    ...
    new Sp\BowerBundle\SpBowerBundle(),
    ...
);
```

3) And here's my bower.json, which lives inside `<Symfony2 Project Name>/src/MyProject/Bundle/SiteBundle/Resources/config/bower/bower.json`.

```
{
    "name": "my-project-site-bundle",
    "dependencies": {
        "jquery": "~2.1.1",
        "foundation": "~5.4.5",
        "qTip2": "~2.2.1",
        "jquery.ui": "~1.11.2",
        "jquery-cookie": "~1.4.1"
    }
}
```

Any idea what I could do to sort out this issue?

p.s. 
• My `public/components` and `public/components/cache` are created when I run `sp:bower:install`
• Symfony version 2.5.6
• bower version.1.3.12
• php version 5.4.34
• I'm following these directions: https://github.com/Spea/SpBowerBundle/blob/master/Resources/doc/index.md
