### ISSUE TITLE
How to define sp_bower - binary path undepending of its environment 

### ISSUE THREAD

**Issue by linslin** [Spea/SpBowerBundle#138]
I'd like to know how to define sp_bower bin path in config undepending of its enviroment. My node PATHs are configured well. 

In that way, "_/usr/bin/bower_" will only works on UNIX / Ubuntu but not for Windows in my case. So, this works very well on Windows "_C:\Users\<WindowsUserName>\AppData\Roaming\npm\bower_" but it will break the other environments. I also dont want to use symbolic links or a secondary config file only for Windows. 

**config.yml**
```
sp_bower:
    assetic: false
    install_on_warmup: false
    bin: // BOWER Path 
```

Thanks in advance!
