### ISSUE TITLE
Cache warmup is slow

### ISSUE THREAD

**Issue by srosato** [Spea/SpBowerBundle#55]
Hi there, I really like the way this bundle eases the integration of bower with Symfony2, but I find it slow when the cache warms up in the dev environment. It takes around 7.5 seconds to warm the cache (according to the profiler) or 4.5 seconds with assetic and install_on_warmup to false while without the bundle it takes me 2.5 seconds from a cleared dev cache. Am I doing something wrong? My current configuration is as follow:

```
sp_bower:
    bin: %kernel.root_dir%/../node_modules/.bin/bower
    install_on_warmup: true
    assetic:
        nest_dependencies:
            jquery-ui: false
    bundles:
        App:
            asset_dir: ../../public/components
```

Even with these configurations disabled it is slow

```
assetic: false
install_on_warmup: false
```

config_dev.yml:

```
assetic:
    use_controller: false
```

because it still needs to create the entire dependency cache

my bower.json:

```
{
    "name": "ftq",
    "dependencies": {
        "html5shiv": "3.7.0",
        "jquery": "1.8.3",
        "jquery-ui": "1.8.23",
        "bootstrap": "2.3.2"
    },
    "devDependencies": {
        "sinon": "1.7.3",
        "jasmine": "1.3.1",
        "jasmine-jquery": "1.5.9",
        "jasmine-sinon": "0.1.0",
        "karma-jasmine": "0.1.3"
    }
}
```

Isn't there a way to recreate the dependency mapping when it actually really needs a refresh? Because changing a single parameter information in a config file will recreate the entire dependency map
