### ISSUE TITLE
RuntimeException while clearing cache

### ISSUE THREAD

**Issue by matheo** [Spea/SpBowerBundle#79]
Is there a problem moving the cache files to app/cache?
It should't huh? because they are not deleted with `cache:clear`.

I'm using a config.yml section like this:

```
sp_bower:
    bundles:
        SonataAdminBundle:
            asset_dir: %kernel.root_dir%/../web/vendor/
            cache:
                %kernel.cache_dir%/../sp_bower/SonataAdminBundle
```

So, `sp:bower:install` runs smoothly but creates an app/cache/de_ folder, and if I try to clear the cache I get this:

```
Dependency cache keys not yet generated, run "app/console sp:bower:install" to initiate the cache: Cached dependencies for "/path/to/my/app/ca  
  che/de_/sp_bower" not found, create it with the method createDependencyMappingCache(). 
```

The `de_` environment?
Thanks in advice
