### ISSUE TITLE
add a configuration parameter for the bower cache storage directory

### ISSUE THREAD

**Issue by ghost** [Spea/SpBowerBundle#98]
during the bower installation phase it creates a cache directory here:

`/path/to/bundles/AcmeBundle/Resources/config/bower/../../public/components/cache`

I don't think it should attempt to write anywhere except the symfony cache and the target asset location.

It is possible to configure these directories via this entry in a `.bowerrc`:

```
{ "storage":{ "packages":"/path/to/cache" } }
```

as per this stackoverflow post: http://stackoverflow.com/questions/17881116/how-to-change-bower-default-cache-git-templates-completion-folder-locations/18564317#18564317

 or this with the bower command itself:

```
--config.storage.packages=/path/to/cache
```

although there could be some problems with that as per this bower issue:
https://github.com/bower/bower/issues/1043 if the build system is not connected to the internet.

This is my first time using bower, so my assessment of how to solve this problem could be incorrect.

**Comment by Wirone** [comment]
What is the correct way to provide custom cache service? In order to fix our issue described in #123 I wanted to set service for cache:

```
sp_bower:
    bundles:
        OurBundle:
            cache:
                id: our_bundle.cache.bower_dependencies
```

```
our_bundle.cache.bower_dependencies:
        class: BPO\OurBundle\Service\Cache\BowerDependenciesCache
        arguments: [ "%kernel.cache_dir%/../bower_dependencies", ".sp_bower.data" ]
```

I always get exception:

```
[RuntimeException]
  Cache service with id [our_bundle.cache.bower_dependencies] not found
```

**Comment by liviucmg** [comment]
I tried using the default `app/cache/(dev|env)` folder, but it gets cleared on every `app/console cache:clear`, as @Spea mentioned.

So, I figured why not use something like `app/cache/bower/(dev|env)`, since `app/cache` is already writeable and `app/cache/bower` does not get cleared automatically.

```yml
sp_bower:
    bundles:
        AppBundle:
            cache: %kernel.cache_dir%/../bower/%kernel.environment%
```

Could there be any downsides to this that I am unaware of?

Thanks!

**Comment by AlmogBaku** [comment]
@liviucmg  that's actually a really good idea! +1

**Comment by AlmogBaku** [comment]
actually i discovered that @liviucmg is a very problematic solution, since the cache should not be created for every environment.
this is the best solution that i found:
```
sp_bower:
    bundles:
        AppBundle:
            cache: %kernel.cache_dir%/../bower
```
